name: Build
 
on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: Android NDK toolchain Setup
      uses: ravinderjangra/android-ndk-toolchain-setup@0.1
      with: 
        api: '21'
        arch: 'arm'
        install-location: 'toolchains'
    - name: Install asciidoc
      run: |
        apt-get install asciidoc
    - name: asciidoc
      run: |
        ./autogen.sh
        ./configure
        make
        make install
    - name: Compressed file
      run: |
        cd home/runner/work/tinyproxy
        tar -cjf tinyproxy.tar.xz tinyproxy
    - name: Upload file
      uses: actions/upload-artifact@master
      with:
        name: tinyproxy.tar.xz
        path: /home/runner/work/tinyproxy/tinyproxy.tar.xz
