name: Build
 
on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: asciidoc Setup
    - uses: mgred/asciidoctor-action@master
      run: pkg install asciidoc
    - name: asciidoc
      run: |
        ./autogen.sh
        ./configure
        make
        make install
    - name: Compressed file
      run: |
        cd home/runner/work/tinyproxy
        tar -cjf tinyproxy.tar.xz tinyproxy
    - name: Upload file
      uses: actions/upload-artifact@master
      with:
        name: tinyproxy.tar.xz
        path: /home/runner/work/tinyproxy/tinyproxy.tar.xz
